# Generated by Django 3.2.4 on 2022-08-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brothers_cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg',
            new_name='registration',
        ),
    ]
