# Generated by Django 3.2.4 on 2022-08-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brothers_cafe', '0005_category_table_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='', upload_to='Brothers_cafe/images'),
        ),
    ]
