# Generated by Django 3.2.4 on 2022-09-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brothers_cafe', '0006_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='profile_photo',
            field=models.ImageField(default='Brothers_cafe/images/download.jfif', upload_to='Brothers_cafe/images'),
        ),
    ]
