# Generated by Django 3.2.4 on 2022-09-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brothers_cafe', '0007_user_registration_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='profile_photo',
            field=models.ImageField(default='Brothers_cafe/static/images/download.jfif', upload_to='Brothers_cafe/images'),
        ),
    ]
