# Generated by Django 3.2.4 on 2022-09-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brothers_cafe', '0008_alter_user_registration_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='abcd.jpeg', null=True, upload_to='')),
                ('category', models.CharField(choices=[('Br', 'Burger'), ('Pz', 'Pizza'), ('Nd', 'Noodles')], default='Pz', max_length=20)),
            ],
        ),
    ]
