# Generated by Django 3.2.4 on 2022-09-18 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brothers_cafe', '0013_auto_20220918_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 11, 58, 15, 356427)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 11, 58, 15, 355429)),
        ),
    ]
