# Generated by Django 3.2.4 on 2022-09-19 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brothers_cafe', '0017_auto_20220918_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_galery', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 12, 31, 11, 243228)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 12, 31, 11, 242232)),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='categoryGalery',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Brothers_cafe.gallerycategory'),
        ),
    ]
