# Generated by Django 3.2.4 on 2022-09-21 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brothers_cafe', '0019_auto_20220919_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 16, 54, 55, 13410)),
        ),
        migrations.RemoveField(
            model_name='food',
            name='dislike',
        ),
        migrations.AddField(
            model_name='food',
            name='dislike',
            field=models.ManyToManyField(related_name='dislike', to='Brothers_cafe.user_registration'),
        ),
        migrations.RemoveField(
            model_name='food',
            name='like',
        ),
        migrations.AddField(
            model_name='food',
            name='like',
            field=models.ManyToManyField(related_name='like', to='Brothers_cafe.user_registration'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 16, 54, 55, 12412)),
        ),
    ]
