# Generated by Django 3.2.4 on 2022-09-25 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brothers_cafe', '0021_auto_20220921_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='Brothers_cafe.food'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 10, 29, 33, 123020)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 10, 29, 33, 122024)),
        ),
    ]
