# Generated by Django 3.2.4 on 2022-10-01 06:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brothers_cafe', '0022_auto_20220925_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_table',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_id',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 11, 48, 56, 181934)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 11, 48, 56, 181934)),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_quantity', models.IntegerField(default=1)),
                ('food_price', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_name', to='Brothers_cafe.user_registration')),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brothers_cafe.food')),
            ],
        ),
    ]
