# Generated by Django 3.2.4 on 2022-10-08 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brothers_cafe', '0023_auto_20221001_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='food_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='food_name',
            field=models.ManyToManyField(to='Brothers_cafe.food'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 12, 3, 29, 103693)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 12, 3, 29, 102694)),
        ),
    ]
